/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 allTestCenterMap.glb
*/

// import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/allTestCenterMap.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[11.83, -11.16, 0]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_18.geometry} material={materials.ID4884} />
            <lineSegments geometry={nodes.mesh_18_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_29_instance_0.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_28_instance_0.geometry} material={materials.ID3856} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_27_instance_0.geometry} material={materials.ID64} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_26_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_25_instance_0.geometry} material={materials.ID92} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_24_instance_0.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_23_instance_0.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_22_instance_0.geometry} material={materials.ID5107} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_21_instance_0.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_20.geometry} material={materials.ID4910} />
            <lineSegments geometry={nodes.mesh_20_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_19_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[9.73, -11.16, 0]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_18.geometry} material={materials.ID4884} />
            <lineSegments geometry={nodes.mesh_18_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_29_instance_1.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_28_instance_1.geometry} material={materials.ID3856} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_27_instance_1.geometry} material={materials.ID64} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_26_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_25_instance_1.geometry} material={materials.ID92} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_24_instance_1.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_23_instance_1.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_22_instance_1.geometry} material={materials.ID5107} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_21_instance_1.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_20.geometry} material={materials.ID4910} />
            <lineSegments geometry={nodes.mesh_20_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_19_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[7.63, -11.16, 0]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_18.geometry} material={materials.ID4884} />
            <lineSegments geometry={nodes.mesh_18_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_29_instance_2.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_28_instance_2.geometry} material={materials.ID3856} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_27_instance_2.geometry} material={materials.ID64} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_26_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_25_instance_2.geometry} material={materials.ID92} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_24_instance_2.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_23_instance_2.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_22_instance_2.geometry} material={materials.ID5107} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_21_instance_2.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_20.geometry} material={materials.ID4910} />
            <lineSegments geometry={nodes.mesh_20_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_19_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[9.02, -6.25, 0]} rotation={[0, 0, -Math.PI]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_42.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_42_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_54_instance_0.geometry} material={materials.ID5191} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_53_instance_0.geometry} material={materials.ID4884} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_52.geometry} material={materials.ID92} />
            <mesh geometry={nodes.mesh_52_1.geometry} material={materials.ID5262} />
          </group>
          <mesh geometry={nodes.mesh_51_instance_0.geometry} material={materials.ID7} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_50_instance_0.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_49_instance_0.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_48_instance_0.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_47_instance_0.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_46_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_45_instance_0.geometry} material={materials.ID5205} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_44.geometry} material={materials.ID3856} />
            <lineSegments geometry={nodes.mesh_44_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_43_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[11.12, -6.25, 0]} rotation={[0, 0, -Math.PI]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_42.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_42_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_54_instance_1.geometry} material={materials.ID5191} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_53_instance_1.geometry} material={materials.ID4884} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_52.geometry} material={materials.ID92} />
            <mesh geometry={nodes.mesh_52_1.geometry} material={materials.ID5262} />
          </group>
          <mesh geometry={nodes.mesh_51_instance_1.geometry} material={materials.ID7} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_50_instance_1.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_49_instance_1.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_48_instance_1.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_47_instance_1.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_46_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_45_instance_1.geometry} material={materials.ID5205} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_44.geometry} material={materials.ID3856} />
            <lineSegments geometry={nodes.mesh_44_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_43_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[13.22, -6.25, 0]} rotation={[0, 0, -Math.PI]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_42.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_42_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_54_instance_2.geometry} material={materials.ID5191} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_53_instance_2.geometry} material={materials.ID4884} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_52.geometry} material={materials.ID92} />
            <mesh geometry={nodes.mesh_52_1.geometry} material={materials.ID5262} />
          </group>
          <mesh geometry={nodes.mesh_51_instance_2.geometry} material={materials.ID7} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_50_instance_2.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_49_instance_2.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_48_instance_2.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_47_instance_2.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_46_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_45_instance_2.geometry} material={materials.ID5205} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_44.geometry} material={materials.ID3856} />
            <lineSegments geometry={nodes.mesh_44_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_43_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[11.93, -4.24, 0]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_30.geometry} material={materials.ID4910} />
            <lineSegments geometry={nodes.mesh_30_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_41_instance_0.geometry} material={materials.ID5107} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_40_instance_0.geometry} material={materials.ID92} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_39_instance_0.geometry} material={materials.ID4884} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_38_instance_0.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_37_instance_0.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_36_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_35_instance_0.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_34_instance_0.geometry} material={materials.ID1292} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_33_instance_0.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_32.geometry} material={materials.ID4910} />
            <mesh geometry={nodes.mesh_32_1.geometry} material={materials.ID3856} />
            <lineSegments geometry={nodes.mesh_32_2.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_31_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[9.78, -4.24, 0]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_30.geometry} material={materials.ID4910} />
            <lineSegments geometry={nodes.mesh_30_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_41_instance_1.geometry} material={materials.ID5107} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_40_instance_1.geometry} material={materials.ID92} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_39_instance_1.geometry} material={materials.ID4884} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_38_instance_1.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_37_instance_1.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_36_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_35_instance_1.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_34_instance_1.geometry} material={materials.ID1292} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_33_instance_1.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_32.geometry} material={materials.ID4910} />
            <mesh geometry={nodes.mesh_32_1.geometry} material={materials.ID3856} />
            <lineSegments geometry={nodes.mesh_32_2.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_31_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[7.63, -4.24, 0]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_30.geometry} material={materials.ID4910} />
            <lineSegments geometry={nodes.mesh_30_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_41_instance_2.geometry} material={materials.ID5107} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_40_instance_2.geometry} material={materials.ID92} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_39_instance_2.geometry} material={materials.ID4884} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_38_instance_2.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_37_instance_2.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_36_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_35_instance_2.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_34_instance_2.geometry} material={materials.ID1292} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_33_instance_2.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_32.geometry} material={materials.ID4910} />
            <mesh geometry={nodes.mesh_32_1.geometry} material={materials.ID3856} />
            <lineSegments geometry={nodes.mesh_32_2.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_31_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[13.23, 1.05, 0]} rotation={[0, 0, -Math.PI]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_18.geometry} material={materials.ID4884} />
            <lineSegments geometry={nodes.mesh_18_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_29_instance_3.geometry} material={materials.ID4985} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_28_instance_3.geometry} material={materials.ID3856} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_27_instance_3.geometry} material={materials.ID64} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_26_instance_3.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_25_instance_3.geometry} material={materials.ID92} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_24_instance_3.geometry} material={materials.ID246} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_23_instance_3.geometry} material={materials.ID282} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_22_instance_3.geometry} material={materials.ID5107} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_21_instance_3.geometry} material={materials.ID9586} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_20.geometry} material={materials.ID4910} />
            <lineSegments geometry={nodes.mesh_20_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_19_instance_3.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-2.16, -1.06, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_0.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_0.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_0.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_0.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_0.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_0.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-2.16, -1.91, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_1.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_1.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_1.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_1.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_1.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_1.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-2.16, -2.89, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_2.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_2.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_2.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_2.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_2.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_2.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-2.16, -3.74, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_3.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_3.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_3.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_3.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_3.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_3.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-3.94, -3.77, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_4.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_4.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_4.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_4.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_4.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_4.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-3.94, -2.91, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_5.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_5.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_5.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_5.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_5.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_5.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-3.94, -1.08, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_6.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_6.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_6.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_6.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_6.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_6.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-3.94, -1.93, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.mesh_11_instance_7.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_7.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_7.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_7.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_7.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_7.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[4.38, -9.75, 0.91]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_0.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_0.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_0.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_0.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_0.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_0.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_0.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_0.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[5.6, -9.75, 0.91]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_1.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_1.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_1.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_1.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_1.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_1.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_1.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_1.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[8.04, -9.75, 0.91]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_2.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_2.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_2.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_2.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_2.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_2.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_2.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_2.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[6.82, -9.75, 0.91]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_3.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_3.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_3.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_3.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_3.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_3.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_3.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_3.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_3.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[1.22, -12.33, 0]} rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes.mesh_11_instance_8.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_8.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_8.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_8.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_8.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_8.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[2.45, -12.33, 0]} rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes.mesh_11_instance_9.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_9.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_9.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_9.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_9.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_9.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[3.67, -12.33, 0]} rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes.mesh_11_instance_10.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_10.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_10.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_10.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_10.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_10.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[4.89, -12.33, 0]} rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes.mesh_11_instance_11.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_11.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_11.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_11.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_11.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_11.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[0.5, -17.83, 0.91]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_4.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_4.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_4.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_4.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_4.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_4.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_4.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_4.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_4.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[1.22, -15.25, 0]}>
          <mesh geometry={nodes.mesh_11_instance_12.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_12.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_12.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_12.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_12.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_12.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-1.94, -17.83, 0.91]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_5.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_5.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_5.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_5.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_5.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_5.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_5.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_5.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_5.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[-0.72, -17.83, 0.91]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_6.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_6.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_6.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_6.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_6.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_6.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_6.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_6.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_6.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[2.44, -15.25, 0]}>
          <mesh geometry={nodes.mesh_11_instance_13.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_13.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_13.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_13.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_13.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_13.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[3.65, -15.25, 0]}>
          <mesh geometry={nodes.mesh_11_instance_14.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_14.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_14.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_14.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_14.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_14.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[4.88, -15.25, 0]}>
          <mesh geometry={nodes.mesh_11_instance_15.geometry} material={materials.ID8522} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_16_instance_15.geometry} material={materials.ID8537} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_15_instance_15.geometry} material={materials.ID8574} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_14_instance_15.geometry} material={materials.ID8597} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_13_instance_15.geometry} material={materials.ID8722} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_12_instance_15.geometry} material={materials.ID8743} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <group position={[1.72, -17.83, 0.91]} rotation={[0, 0, -Math.PI / 2]}>
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.ID8861} />
            <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID8866} />
          </group>
          <mesh geometry={nodes.mesh_10_instance_7.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_9_instance_7.geometry} material={materials.ID8925} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_8_instance_7.geometry} material={materials.ID8861} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_7_instance_7.geometry} material={materials.ID9014} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_6_instance_7.geometry} material={materials.ID9061} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_5_instance_7.geometry} material={materials.ID9092} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_4_instance_7.geometry} material={materials.ID8995} position={[-14.87, -0.35, -15.76]} scale={0} />
          <mesh geometry={nodes.mesh_3_instance_7.geometry} material={materials.ID9009} position={[-14.87, -0.35, -15.76]} scale={0} />
          <group position={[-14.87, -0.35, -15.76]} scale={0}>
            <mesh geometry={nodes.mesh_2.geometry} material={materials.ID9586} />
            <lineSegments geometry={nodes.mesh_2_1.geometry} material={materials.ID8866} />
          </group>
          <lineSegments geometry={nodes.mesh_1_instance_7.geometry} material={materials.ID8866} position={[-14.87, -0.35, -15.76]} scale={0} />
        </group>
        <OrthographicCamera makeDefault={false} far={25.4} near={0.03} position={[-126777.95, -145020.61, 207373.78]} rotation={[0.61, -0.46, -0.57]} />
      </group>
      <group position={[-14.87, -0.35, -15.76]} scale={0}>
        <mesh geometry={nodes.mesh_17.geometry} material={materials.ID8470} />
        <lineSegments geometry={nodes.mesh_17_1.geometry} material={materials.ID8866} />
        <mesh geometry={nodes.mesh_17_2.geometry} material={materials.ID8507} />
        <mesh geometry={nodes.mesh_17_3.geometry} material={materials.ID8492} />
        <mesh geometry={nodes.mesh_17_4.geometry} material={materials.ID8331} />
        <lineSegments geometry={nodes.mesh_17_5.geometry} material={materials.ID8866} />
        <mesh geometry={nodes.mesh_17_6.geometry} material={materials.ID282} />
        <mesh geometry={nodes.mesh_17_7.geometry} material={materials.ID92} />
        <mesh geometry={nodes.mesh_17_8.geometry} material={materials.ID1292} />
        <mesh geometry={nodes.mesh_17_9.geometry} material={materials.ID9586} />
        <mesh geometry={nodes.mesh_17_10.geometry} material={materials.ID8383} />
        <mesh geometry={nodes.mesh_17_11.geometry} material={materials.ID246} />
        <mesh geometry={nodes.mesh_17_12.geometry} material={materials.ID8231} />
        <mesh geometry={nodes.mesh_17_13.geometry} material={materials.ID8300} />
        <mesh geometry={nodes.mesh_17_14.geometry} material={materials.ID8244} />
        <mesh geometry={nodes.mesh_17_15.geometry} material={materials.ID8866} />
        <mesh geometry={nodes.mesh_17_16.geometry} material={materials.ID8011} />
        <mesh geometry={nodes.mesh_17_17.geometry} material={materials.ID8020} />
        <mesh geometry={nodes.mesh_17_18.geometry} material={materials.ID8120} />
        <mesh geometry={nodes.mesh_17_19.geometry} material={materials.ID64} />
        <mesh geometry={nodes.mesh_17_20.geometry} material={materials.ID8065} />
        <mesh geometry={nodes.mesh_17_21.geometry} material={materials.ID3856} />
        <mesh geometry={nodes.mesh_17_22.geometry} material={materials.ID7936} />
        <mesh geometry={nodes.mesh_17_23.geometry} material={materials.ID8995} />
        <mesh geometry={nodes.mesh_17_24.geometry} material={materials.ID3832} />
        <mesh geometry={nodes.mesh_17_25.geometry} material={materials.ID164} />
        <mesh geometry={nodes.mesh_17_26.geometry} material={materials.ID1719} />
        <mesh geometry={nodes.mesh_17_27.geometry} material={materials.ID6165} />
        <mesh geometry={nodes.mesh_17_28.geometry} material={materials.ID5191} />
        <mesh geometry={nodes.mesh_17_29.geometry} material={materials.ID2062} />
      </group>
      <group position={[-14.87, -0.35, -15.76]} scale={0}>
        <mesh geometry={nodes.mesh_55.geometry} material={materials.ID7} />
        <mesh geometry={nodes.mesh_55_1.geometry} material={materials.ID1517} />
        <mesh geometry={nodes.mesh_55_2.geometry} material={materials.ID1980} />
        <mesh geometry={nodes.mesh_55_3.geometry} material={materials.ID212} />
        <mesh geometry={nodes.mesh_55_4.geometry} material={materials.ID134} />
        <mesh geometry={nodes.mesh_55_5.geometry} material={materials.ID2026} />
        <mesh geometry={nodes.mesh_55_6.geometry} material={materials.ID2092} />
        <mesh geometry={nodes.mesh_55_7.geometry} material={materials.ID2078} />
        <mesh geometry={nodes.mesh_55_8.geometry} material={materials.ID1589} />
        <mesh geometry={nodes.mesh_55_9.geometry} material={materials.ID1597} />
        <mesh geometry={nodes.mesh_55_10.geometry} material={materials.ID1539} />
        <mesh geometry={nodes.mesh_55_11.geometry} material={materials.ID1366} />
        <mesh geometry={nodes.mesh_55_12.geometry} material={materials.ID1334} />
        <mesh geometry={nodes.mesh_55_13.geometry} material={materials.ID84} />
        <mesh geometry={nodes.mesh_55_14.geometry} material={materials.ID398} />
        <mesh geometry={nodes.mesh_55_15.geometry} material={materials.ID269} />
        <mesh geometry={nodes.mesh_55_16.geometry} material={materials.ID196} />
        <mesh geometry={nodes.mesh_55_17.geometry} material={materials.ID124} />
        <mesh geometry={nodes.mesh_55_18.geometry} material={materials.ID116} />
      </group>
    </group>
  )
}

useGLTF.preload('/allTestCenterMap.glb')
