/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 building.glb
*/

// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/building.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.wall_roof_rollup2.geometry} material={nodes.wall_roof_rollup2.material} />
        <mesh geometry={nodes.asphalt3.geometry} material={nodes.asphalt3.material} />
        <mesh geometry={nodes.brick4.geometry} material={nodes.brick4.material} />
        <mesh geometry={nodes.cornices_and_trim5.geometry} material={nodes.cornices_and_trim5.material} />
        <mesh geometry={nodes.other_bits6.geometry} material={nodes.other_bits6.material} />
        <mesh geometry={nodes.concrete7.geometry} material={nodes.concrete7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/building.glb')
