/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 null.glb
*/

// import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/null.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <OrthographicCamera makeDefault={false} far={25.4} near={0.03} position={[3.01, -10.63, 16.05]} rotation={[0.6, 0.19, 0.27]} />
      </group>
      <group position={[-0.75, 0, -0.9]} scale={0}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.ID23} />
        <lineSegments geometry={nodes.mesh_0_1.geometry} material={materials.ID12} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={materials.ID12} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={materials.ID34} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={materials.ID55} />
      </group>
    </group>
  )
}

useGLTF.preload('/null.glb')
