/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 test.glb
*/

// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/test.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <mesh geometry={nodes.ID3.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID3_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID24.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID24_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID34.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID34_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID44.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID44_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID54.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID54_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID64.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID64_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID74.geometry} material={materials.material} />
        <mesh geometry={nodes.ID74_1.geometry} material={materials.Color_M05} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID86.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID86_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID96.geometry} material={materials.material} />
        <mesh geometry={nodes.ID96_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID106.geometry} material={materials.material} />
        <mesh geometry={nodes.ID106_1.geometry} material={materials.Translucent_Glass_Blue} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID116.geometry} material={materials.material} />
        <mesh geometry={nodes.ID116_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID124.geometry} material={materials.material} />
        <mesh geometry={nodes.ID124_1.geometry} material={materials.Color_M00} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID136.geometry} material={materials.material} />
        <mesh geometry={nodes.ID136_1.geometry} material={materials.Color_G05} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID146.geometry} material={materials.material} />
        <mesh geometry={nodes.ID146_1.geometry} material={materials.Color_F04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID158.geometry} material={materials.material} />
        <mesh geometry={nodes.ID158_1.geometry} material={materials.Color_D05} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID168.geometry} material={materials.material} />
        <mesh geometry={nodes.ID168_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID180.geometry} material={materials.material} />
        <mesh geometry={nodes.ID180_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID188.geometry} material={materials.material} />
        <mesh geometry={nodes.ID188_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID196.geometry} material={materials.material} />
        <mesh geometry={nodes.ID196_1.geometry} material={materials.Color_B05} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID206.geometry} material={materials.material} />
        <mesh geometry={nodes.ID206_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID214.geometry} material={materials.material} />
        <mesh geometry={nodes.ID214_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID222.geometry} material={materials.material} />
        <mesh geometry={nodes.ID222_1.geometry} material={materials.Color_M05} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID230.geometry} material={materials.material} />
        <mesh geometry={nodes.ID230_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID238.geometry} material={materials.material} />
        <mesh geometry={nodes.ID238_1.geometry} material={materials.Color_E04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID248.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID248_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID258.geometry} material={materials.material} />
        <mesh geometry={nodes.ID258_1.geometry} material={materials.Color_A06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID268.geometry} material={materials.material} />
        <mesh geometry={nodes.ID268_1.geometry} material={materials.Color_M07} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID278.geometry} material={materials.material} />
        <mesh geometry={nodes.ID278_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID286.geometry} material={materials.material} />
        <mesh geometry={nodes.ID286_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID294.geometry} material={materials.material} />
        <mesh geometry={nodes.ID294_1.geometry} material={materials.Color_M07} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID302.geometry} material={materials.material} />
        <mesh geometry={nodes.ID302_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID312.geometry} material={materials.material} />
        <mesh geometry={nodes.ID312_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID320.geometry} material={materials.material} />
        <mesh geometry={nodes.ID320_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID328.geometry} material={materials.Color_M00} />
        <mesh geometry={nodes.ID328_1.geometry} material={materials.Color_F03} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID338.geometry} material={materials.material} />
        <mesh geometry={nodes.ID338_1.geometry} material={materials.Color_M07} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID348.geometry} material={materials.material} />
        <mesh geometry={nodes.ID348_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID358.geometry} material={materials.material} />
        <mesh geometry={nodes.ID358_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID366.geometry} material={materials.material} />
        <mesh geometry={nodes.ID366_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID374.geometry} material={materials.material} />
        <mesh geometry={nodes.ID374_1.geometry} material={materials.Color_M07} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID382.geometry} material={materials.material} />
        <mesh geometry={nodes.ID382_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID390.geometry} material={materials.material} />
        <mesh geometry={nodes.ID390_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID398.geometry} material={materials.material} />
        <mesh geometry={nodes.ID398_1.geometry} material={materials.Color_F03} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID406.geometry} material={materials.material} />
        <mesh geometry={nodes.ID406_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID414.geometry} material={materials.material} />
        <mesh geometry={nodes.ID414_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID422.geometry} material={materials.material} />
        <mesh geometry={nodes.ID422_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID430.geometry} material={materials.material} />
        <mesh geometry={nodes.ID430_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID438.geometry} material={materials.material} />
        <mesh geometry={nodes.ID438_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID446.geometry} material={materials.material} />
        <mesh geometry={nodes.ID446_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID454.geometry} material={materials.material} />
        <mesh geometry={nodes.ID454_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID462.geometry} material={materials.material} />
        <mesh geometry={nodes.ID462_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID470.geometry} material={materials.material} />
        <mesh geometry={nodes.ID470_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID478.geometry} material={materials.material} />
        <mesh geometry={nodes.ID478_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID486.geometry} material={materials.material} />
        <mesh geometry={nodes.ID486_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID494.geometry} material={materials.material} />
        <mesh geometry={nodes.ID494_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID502.geometry} material={materials.material} />
        <mesh geometry={nodes.ID502_1.geometry} material={materials.Color_H03} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID512.geometry} material={materials.material} />
        <mesh geometry={nodes.ID512_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID520.geometry} material={materials.material} />
        <mesh geometry={nodes.ID520_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID528.geometry} material={materials.material} />
        <mesh geometry={nodes.ID528_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID536.geometry} material={materials.material} />
        <mesh geometry={nodes.ID536_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID544.geometry} material={materials.material} />
        <mesh geometry={nodes.ID544_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID552.geometry} material={materials.material} />
        <mesh geometry={nodes.ID552_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID560.geometry} material={materials.material} />
        <mesh geometry={nodes.ID560_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID568.geometry} material={materials.material} />
        <mesh geometry={nodes.ID568_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID576.geometry} material={materials.material} />
        <mesh geometry={nodes.ID576_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID584.geometry} material={materials.material} />
        <mesh geometry={nodes.ID584_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID592.geometry} material={materials.material} />
        <mesh geometry={nodes.ID592_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID600.geometry} material={materials.material} />
        <mesh geometry={nodes.ID600_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID608.geometry} material={materials.material} />
        <mesh geometry={nodes.ID608_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID616.geometry} material={materials.material} />
        <mesh geometry={nodes.ID616_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID624.geometry} material={materials.material} />
        <mesh geometry={nodes.ID624_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID632.geometry} material={materials.material} />
        <mesh geometry={nodes.ID632_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID640.geometry} material={materials.material} />
        <mesh geometry={nodes.ID640_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID648.geometry} material={materials.material} />
        <mesh geometry={nodes.ID648_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID656.geometry} material={materials.material} />
        <mesh geometry={nodes.ID656_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID664.geometry} material={materials.material} />
        <mesh geometry={nodes.ID664_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID672.geometry} material={materials.material} />
        <mesh geometry={nodes.ID672_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID680.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID680_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID690.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID690_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID700.geometry} material={materials.material} />
        <mesh geometry={nodes.ID700_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID708.geometry} material={materials.material} />
        <mesh geometry={nodes.ID708_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID716.geometry} material={materials.material} />
        <mesh geometry={nodes.ID716_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID724.geometry} material={materials.material} />
        <mesh geometry={nodes.ID724_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID732.geometry} material={materials.material} />
        <mesh geometry={nodes.ID732_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID740.geometry} material={materials.material} />
        <mesh geometry={nodes.ID740_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID748.geometry} material={materials.material} />
        <mesh geometry={nodes.ID748_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID756.geometry} material={materials.material} />
        <mesh geometry={nodes.ID756_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID764.geometry} material={materials.material} />
        <mesh geometry={nodes.ID764_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID772.geometry} material={materials.material} />
        <mesh geometry={nodes.ID772_1.geometry} material={materials.Color_M00} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID780.geometry} material={materials.material} />
        <mesh geometry={nodes.ID780_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID788.geometry} material={materials.material} />
        <mesh geometry={nodes.ID788_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID796.geometry} material={materials.material} />
        <mesh geometry={nodes.ID796_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID804.geometry} material={materials.material} />
        <mesh geometry={nodes.ID804_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID812.geometry} material={materials.material} />
        <mesh geometry={nodes.ID812_1.geometry} material={materials.Color_M00} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID820.geometry} material={materials.material} />
        <mesh geometry={nodes.ID820_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID828.geometry} material={materials.material} />
        <mesh geometry={nodes.ID828_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID836.geometry} material={materials.material} />
        <mesh geometry={nodes.ID836_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID844.geometry} material={materials.material} />
        <mesh geometry={nodes.ID844_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID852.geometry} material={materials.material} />
        <mesh geometry={nodes.ID852_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID860.geometry} material={materials.material} />
        <mesh geometry={nodes.ID860_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID868.geometry} material={materials.material} />
        <mesh geometry={nodes.ID868_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID876.geometry} material={materials.material} />
        <mesh geometry={nodes.ID876_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID884.geometry} material={materials.material} />
        <mesh geometry={nodes.ID884_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID892.geometry} material={materials.material} />
        <mesh geometry={nodes.ID892_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID900.geometry} material={materials.material} />
        <mesh geometry={nodes.ID900_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID908.geometry} material={materials.material} />
        <mesh geometry={nodes.ID908_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID916.geometry} material={materials.material} />
        <mesh geometry={nodes.ID916_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID924.geometry} material={materials.material} />
        <mesh geometry={nodes.ID924_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID932.geometry} material={materials.material} />
        <mesh geometry={nodes.ID932_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID940.geometry} material={materials.material} />
        <mesh geometry={nodes.ID940_1.geometry} material={materials.Color_M06} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID948.geometry} material={materials.material} />
        <mesh geometry={nodes.ID948_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID956.geometry} material={materials.material} />
        <mesh geometry={nodes.ID956_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID964.geometry} material={materials.material} />
        <mesh geometry={nodes.ID964_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID972.geometry} material={materials.material} />
        <mesh geometry={nodes.ID972_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID980.geometry} material={materials.material} />
        <mesh geometry={nodes.ID980_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID988.geometry} material={materials.material} />
        <mesh geometry={nodes.ID988_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID996.geometry} material={materials.material} />
        <mesh geometry={nodes.ID996_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1004.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1004_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1012.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1012_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1020.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1020_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1028.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1028_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1036.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1036_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1044.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1044_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1052.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1052_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1060.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1060_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1068.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1068_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1076.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1076_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1084.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1084_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1092.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1092_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1100.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1100_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1108.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1108_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1116.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1116_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1124.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1124_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1132.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1132_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1140.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1140_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1148.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1148_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1156.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1156_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1164.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1164_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1172.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1172_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1180.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1180_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1188.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1188_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1196.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1196_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1204.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1204_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1212.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1212_1.geometry} material={materials.__Color_M03_1} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1220.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1220_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1228.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1228_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1236.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1236_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1244.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1244_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1252.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1252_1.geometry} material={materials.Color_M04} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1260.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1260_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1270.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1270_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1280.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1280_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1290.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1290_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1300.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1300_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1310.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1310_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1320.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1320_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1330.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1330_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1340.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1340_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1350.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1350_1.geometry} material={materials.Color_M05} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1358.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1358_1.geometry} material={materials.Translucent_Glass_Blue} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1366.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1366_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1376.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1376_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1386.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1386_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1396.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1396_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1406.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1406_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1416.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1416_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1426.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1426_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1436.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1436_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1446.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1446_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1456.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1456_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1466.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1466_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1476.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1476_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1486.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1486_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1496.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1496_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1506.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1506_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1516.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1516_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1526.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1526_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1536.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1536_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1546.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1546_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1556.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1556_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1566.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1566_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1576.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1576_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1586.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1586_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1596.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1596_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1606.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1606_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1616.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1616_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1626.geometry} material={materials.Metal_Silver} />
        <mesh geometry={nodes.ID1626_1.geometry} material={materials.material} />
      </group>
      <group scale={0.03}>
        <mesh geometry={nodes.ID1636.geometry} material={materials.material} />
        <mesh geometry={nodes.ID1636_1.geometry} material={materials.Color_M05} />
      </group>
    </group>
  )
}

useGLTF.preload('/test.glb')
